### ISSUE TITLE
Merging collision shapes

### ISSUE THREAD

**Issue by SammyRamone** [Rhoban/onshape-to-robot#36]
Currently using the "mergeSTLs" option will only merge the visual stls in an URDF. The collision will still consist out of multiple stl files.
Is this intended behaviour? 
If yes please document it better in the documentation by stating that only visual stls are merged.
Otherwise, I did a small hack to make it work (which should not be merged upstream due to bad code quality): https://github.com/bit-bots/onshape-to-robot/commit/390ea00f6b22261d9d5d0055143215ea9659d3dd
It works but for my model I had to deactivate collision with parents (using the `URDF_USE_SELF_COLLISION_EXCLUDE_ALL_PARENTS` flag) since it would lead to some self collisions otherwise.

**Comment by Gregwar** [comment]
I finally added that possibility

Now both `mergeSTLs` and `simplifySTLs` can be `"no"`, `"visual"`, `"collision"` or `"all"`
https://onshape-to-robot.readthedocs.io/en/latest/config.html#mergestls
