### ISSUE TITLE
Allow links to contain "composite parts"

### ISSUE THREAD

**Issue by super-ste** [Rhoban/onshape-to-robot#38]
[Composite Parts](https://cad.onshape.com/help/Content/composite_part.htm) are a relatively new addition to OnShape and are super useful to import standard parts in your robot. They can be assigned a material and a mass (for "closed composite") or behave as assemblies (therefore weighting as the sum of the components (for "open composite").

To allow composite parts to behave as "normal parts" just a single line needs changing:

https://github.com/Rhoban/onshape-to-robot/blob/dc5585cc724afda3c8764799a68d0fd7b3398760/onshape_to_robot/onshape_api/client.py#L167

add 'includeNonSolids' to the list of the queries

`return self._api.request('get', '/api/assemblies/d/'+did+'/'+type+'/'+wid+'/e/'+eid, query={'includeMateFeatures': 'true', 'includeNonSolids': 'true'}).json()`

**Comment by Gregwar** [comment]
Ok, thanks for contributing!
