### ISSUE TITLE
Unable to find assembly in this document

### ISSUE THREAD

**Issue by RDaneelOlivav** [Rhoban/onshape-to-robot#8]
I'm getting this error: 

> Unable to find assembly in this document

I think it's getting to the page but for some reason, it's not finding the assembly.
Does anyone have any suggestions that might give e a workaround of this? Thanks!

**Comment by RDaneelOlivav** [comment]
Ok, I solved it by just removing the assembly name in the config file. There might be something strange in the name search

**Comment by Gregwar** [comment]
Yes, sorry, there was some comparsion with the lowercase name of the element
I fixed that a couple of weeks ago but didnt push

Just done that fix in f8cff48d3dcf670a5a21a38f3dcee9c57e0da2e1

Thanks for reporting
